name: BP Great Games Today Post

on:
  schedule:
    - cron: '0 5 * * 4'  # Thu 5:00 UTC = Wed 9:00pm PST, newbie
    - cron: '0 3 * * 1'  # Every Sun 7pm PST (Mon 3am UTC), pickup
    - cron: '0 3 * * 0'  # Sat 7pm PST  (Sun 3am UTC), newbie
  workflow_dispatch:      # Optional: allows manual run

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run Slack script
        run: python slack/206bikepolo/great_games_today.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          #CHANNEL_ID: ${{ github.event.schedule == '0 3 * * 1' && secrets.CHANNEL_ID_PICKUP || secrets.CHANNEL_ID_NEWBIE }}
          #CHANNEL_ID: ${{ secrets.CHANNEL_ID_NEWBIE }}
          CHANNEL_ID: ${{ github.event.schedule == '0 3 * * 1' && secrets.CHANNEL_ID_PICKUP || secrets.CHANNEL_ID_WEBSITE }}
          #CHANNEL_ID: ${{ secrets.CHANNEL_ID_WEBSITE }}
