name: BP Gamenight Invite DM
on:
  workflow_dispatch:

jobs:
  send_dm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install UV 
        run: pip install uv

      - name: Install dependencies
        run: pip install .

      - name: Run Slack DM script
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: uv run python slack/206bikepolo/gamenight/github_invite_dm.py
