name: Run Discord Subscribe Bot

concurrency:
  group: subscribe-workflow
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # lets you manually trigger

jobs:
  bot:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./discord/byobg
    env:
      BOT_TOKEN: ${{ secrets.BYOBG_BOT_TOKEN }}
      TARGET_USER_ID: ${{ secrets.ABGUP_USER_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install UV 
        run: pip install uv

      - name: Create Virtual Environment
        run: uv venv

      - name: Activate venv
        run: source .venv/bin/activate

      - name: Install dependencies
        run: uv pip install discord.py

      - name: Run script
        run: uv run python subscribe.py
