name: Run Discord Subscribe Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # lets you manually trigger

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Start UV environment && run script
        working-directory: ./discord/byobg
        env:
          BOT_TOKEN: ${{ secrets.BYOBG_BOT_TOKEN }}
          TARGET_USER_ID: ${{ secrets.ABGUP_USER_ID }}
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install discord.py
          uv run python subscribe.py
