name: Run Discord Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # lets you manually trigger

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install UV
        run: pip install uv

      - name: Create UV virtual environment
        working-directory: ./discord/byobg
        run: |
          uv venv
          source .venv/bin/activate

      - name: Install dependencies via UV
        working-directory: ./discord/byobg  # <-- path to folder with pyproject.toml
        run: uv pip install discord.py

      - name: Run bot
        working-directory: ./discord/byobg  # <-- same folder
        env:
          BOT_TOKEN: ${{ secrets.BYOBG_BOT_TOKEN }}
        run: uv run python dm-invite.py
